gogi_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from store.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('store/', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from .views import index, all_electronics, product_info, about, delivery_info, guarantee, trade_in, regularcustomers, \
    contacts

app_name = 'store'

urlpatterns = [
    path('all_electronics/', all_electronics, name='all_electronics'),
    path('all-electronics/category_id:<int:category_id>', all_electronics, name='categories'),
    path('all-electronics/brand_id:<int:brand_id>', all_electronics, name='brands'),
    path('product_info/product_id:<int:product_id>', product_info, name='product_info'),
    path('about/', about, name='about'),
    path('delivery_info/', delivery_info, name='delivery_info'),
    path('guarantee/', guarantee, name='guarantee'),
    path('trade_in/', trade_in, name='trade_in'),
    path('regularcustomers/', regularcustomers, name='regularcustomers'),
    path('contacts/', contacts, name='contacts'),

]

store/models.py
from django.db import models


# Create your models here.


class Brand(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return f'{self.name}'


class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(to=Brand, on_delete=models.CASCADE, blank=True, null=True)
    price = models.IntegerField()
    color = models.CharField(max_length=50)
    memory = models.IntegerField()
    image = models.ImageField(upload_to='products_images', blank=True, null=True)
    sim = models.BooleanField(default=True)
    esim = models.BooleanField(default=False)
    origin_country = models.CharField(max_length=50)
    materials = models.TextField(blank=True, null=True)
    os = models.CharField(max_length=20)
    vendor_code = models.IntegerField()
    guarantee = models.IntegerField()
    nfc = models.BooleanField(default=True)
    description = models.TextField()

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return f'{self.name}'

store/views.py
from django.shortcuts import render

from .models import Product, Category, Brand

# Create your views here.


def index(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    return render(request, 'store/index.html', context)


def all_electronics(request, category_id=None, brand_id=None):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    if category_id and (brand_id is None):
        products = Product.objects.filter(category_id=category_id)
        context['products'] = products
    elif (category_id is None) and brand_id:
        products = Product.objects.filter(brand_id=brand_id)
        context['products'] = products
    else:
        products = Product.objects.all()
        context['products'] = products

    return render(request, 'store/all-electronics.html', context)


def product_info(request, product_id):
    categories = Category.objects.all()
    brands = Brand.objects.all()
    product = Product.objects.get(id=product_id)
    similar_products = Product.objects.filter(brand_id=product.brand.id).order_by('?')[:5]

    context = {
        'categories': categories,
        'brands': brands,
        'product': product,
        'similar_products': similar_products,
    }

    return render(request, 'store/product_info.html', context)


def about(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    return render(request, 'store/about.html', context)


def delivery_info(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    return render(request, 'store/delivery.html', context)


def guarantee(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    return render(request, 'store/guarantee.html', context)


def trade_in(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    return render(request, 'store/trade_in.html', context)


def regularcustomers(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    return render(request, 'store/regularcustomers.html', context)


def contacts(request):
    categories = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'categories': categories,
        'brands': brands,
    }

    return render(request, 'store/contacts.html', context)

store/templates/store/about.html
{% extends 'store/base.html' %}

{% load static %}

{% block content %}
<main style="background-color: rgb(247, 247, 247)">
      <div class="container" style="padding-top: 0.5%">
        <a
          class="fst-italic link-dark fw-normal"
          href="{% url 'index' %}"
          style="text-decoration: none"
          >Главная</a> > <span class="fst-italic link-dark fw-normal">О компании</span>
      </div>
      <div class="container" style="padding-top: 1.5%">
        <p class="text-start fs-4">
          Добро пожаловать на сайт маркетплейса Gadget Store!
          <br />
        </p>
        <p class="fs-5 text-start">
          Будучи далеко не новичками на рынке, мы хорошо знаем, чего хочет наш
          потенциальный клиент, поэтому Gadget Store - это не просто
          онлайн-каталог товаров. Мы идём в ногу со временем, поэтому наш ресурс
          сейчас совмещает в себе маркетплейс и информационный портал, где
          помимо самой свежей информации о новинках, вы найдёте качественные
          видео обзоры, советы по настройке и использованию оборудования,
          новости, обзоры фильмов, игр и другой развлекательный контент.
        </p>
        <p class="text-start fs-4">
          Gadget Store - это качественный сервис и индивидуальный подход к
          каждому клиенту!
        </p>
        <p class="text-start fs-5">
          Мы не гонимся за быстрой выгодой, поэтому результат нашей работы -
          сотни довольных клиентов, которые советуют нас своим друзьям и
          близким. Мы делаем всё, чтобы бренд Gadget Store ассоциировался со
          словами "надёжность" и "качество". Мы тщательно отбираем товары,
          которые предлагаем своим покупателям. На витринах нашего маркетплейса
          вы найдёте только самые лучшие и актуальные устройства и аксессуары
          различных производителей. Все заказы доставляются курьерской службой в
          кратчайшие сроки по всей России. Если вы находитесь в Москве или
          ближайшем Подмосковье, заказ вам привезёт курьер.
        </p>
        <p class="text-start fs-4">
          Gadget Store - это маркетплейс с огромным выбором!
        </p>
        <p class="text-start fs-5">
          В нашем каталоге вы найдёте огромное количество аксессуаров
          известнейших брендов от разных магазинов. Это значит, что вам не нужно
          тратить лишнее время, ломая голову над тем, где бы купить плёнку или
          чехол для вашего гаджета. Достаточно сделать заказ на сайте Gadget
          Store или по телефону. Если же при заказе возникли сомнения, или вы
          просто-напросто не можете определиться, курьер всегда может привезти
          несколько вариантов на выбор (возможность доступна для клиентов из
          Москвы и ближайшего Подмосковья). Стараясь угодить клиенту, мы
          постоянно расширяем ассортимент товаров, привлекая новых партнёров.
        </p>
        <p class="text-start fs-4">
          Gadget Store - это маркетплейс с демократичными ценами!
        </p>
        <p class="text-start fs-5">
          Мы не гонимся за сиюминутной выгодой и ответственно относимся к выбору
          партнёров, поэтому цены на сайте весьма демократичны. Мы не идём на
          различные уловки, которыми пользуются наши конкуренты, не размещаем
          товары сомнительного качества и не навязываем дорогостоящие услуги и
          аксессуары. Цены, по которым продаются товары, позволяют предложить
          вам официальную и качественную продукцию, за которую мы ручаемся
          гарантией и своим именем.
        </p>
      </div>
      <nav class="navbar navbar-expand-lg" style="padding-top: 2%">
        <div class="container shadow" style="background-color: #745eac">
          <div class="collapse navbar-collapse p-5" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 mx-auto">
              <li style="width: 254px; margin-right: 10px">
                <a>
                  <p1 class="fs-5 text-white fw-normal">Быстрая доставка</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Вслушайтесь и вы услышите<br />
                    как торопится наш курьер!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 0px">
                <a>
                  <p1 class="fs-5 text-white"> Простой возврат</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Мы поможем вам с этим, <br />если что-то пошло не так!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 0x">
                <a>
                  <p1 class="fs-5 text-white fw-normal"> Скидки и акции</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Каждый день, специально <br />для вас!
                  </h1></a
                >
              </li>
              <li style="width: 254px; margin-left: 10px">
                <a
                  ><p1 class="fs-5 text-white"> Консьерж-сервис</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Помощь при выборе и эксплуатации вашего гаджета!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 10px">
                <a
                  ><p1 class="fs-5 text-white"> Мы классные</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    С нами так приятно <br />
                    иметь дело!
                  </h1></a
                >
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <footer class="text-center text-lg-start bg-light text-muted">
        <section
          class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
        ></section>
        <section class="">
          <div class="container text-center text-md-start mt-3">
            <div class="row mt-3">
              <div class="col-md-3 col-lg-4 col-xl-4 mx-auto mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">
                  <i class="fas fa-gem"></i>GadgetStore
                </h6>
                <p>
                  Мы всегда стремимся найти самых выгодных поставщиков, поэтому
                  наши цены такие низкие. Более 1000 клиентов по всей России,
                  попробуйте и Вы!
                </p>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">О нас</h6>
                <p>
                  <a href="about.html" class="text-reset">О компании</a>
                </p>
                <p>
                  <a href="delivery.html" class="text-reset">Доставка</a>
                </p>
                <p>
                  <a href="guarantee.html" class="text-reset">Гарантия</a>
                </p>
                <p>
                  <a href="TradeIN.html" class="text-reset">Trade In</a>
                </p>
              </div>

              <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">Контакты</h6>
                <p>
                  <i class="fas fa-home"></i> Москва, Багратионовский проезд, д.
                  7 к. 20В, Б.Ц. "Конвент", офис 711 (7 этаж)
                </p>
                <p>
                  <i class="fas fa-envelope"></i>
                  info@GadgetStore.ru
                </p>
                <p><i class="fas fa-phone"></i> 8(915)·252·58·59</p>
                <p><i class="fas fa-print"></i> 8(800)·555·35·35</p>
              </div>
            </div>
          </div>
        </section>
        <div
          class="text-center p-3"
          style="background-color: rgb(240, 239, 239)"
        >
          © 2022 Авторские права:
          <a class="text-reset fw-bold" href="https://mdbootstrap.com/"
            >NodeathMod</a
          >
        </div>
      </footer>
    </main>
{% endblock %}

store/templates/store/all-electronics.html
{% extends 'store/base.html' %}

{% load static %}

{% block content%}
    <main style="background-color: rgb(247, 247, 247)">
      <div class="container" style="padding-top: 0.5%">
        <a
          class="fst-italic link-dark fw-normal"
          href="{% url 'index' %}"
          style="text-decoration: none"
          >Главная</a> > <span class="fst-italic link-dark fw-normal">Вся электроника</span>
      </div>
      <div class="container my-4">
        <p class="fs-1">Вся электроника</p>
        <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-4 my-3">
          {% for product in products %}
            <div class="col">
              <a
                href="{% url 'store:product_info' product.id %}"
                style="color: black; text-decoration: none"
              >
                <div class="card catside">
                  <img
                    src="{{ product.image.url }}"
                    class="card-img-top"
                    alt="my image"
                    style="width: 230px; height: 238px;"
                  />
                  <div class="card-body">
                    <h5 class="card-title text-center fs-6 fw-normal">
                      {{ product.name }}<br />
                      {{ product.memory }}GB <br />({{ product.color }})
                    </h5>
                    <h class="fs-5 fw-semibold">{{ product.price }} ₽</h>
                    <a
                      href="basketsuccess.html"
                      style="
                        width: 100px;
                        margin-left: 25%;
                        text-decoration: none;
                      "
                      class="fs-5 fw-semibold link-secondary text-primary"
                      >Купить
                    </a>
                  </div>
                </div>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
      <nav aria-label="Page navigation example" style="margin-left: 47%">
        <ul class="pagination">
          <li class="page-item">
            <a class="page-link" href="All electronics.html">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="all electronics2.html">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="all electronics2.html" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
      <nav class="navbar navbar-expand-lg" style="padding-top: 2%">
        <div class="container shadow" style="background-color: #745eac">
          <div class="collapse navbar-collapse p-5" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 mx-auto">
              <li style="width: 254px; margin-right: 10px">
                <a>
                  <p1 class="fs-5 text-white fw-normal">Быстрая доставка</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Вслушайтесь и вы услышите<br />
                    как торопится наш курьер!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 0px">
                <a>
                  <p1 class="fs-5 text-white"> Простой возврат</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Мы поможем вам с этим, <br />если что-то пошло не так!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 0x">
                <a>
                  <p1 class="fs-5 text-white fw-normal"> Скидки и акции</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Каждый день, специально <br />для вас!
                  </h1></a
                >
              </li>
              <li style="width: 254px; margin-left: 10px">
                <a
                  ><p1 class="fs-5 text-white"> Консьерж-сервис</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Помощь при выборе и эксплуатации вашего гаджета!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 10px">
                <a
                  ><p1 class="fs-5 text-white"> Мы классные</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    С нами так приятно <br />
                    иметь дело!
                  </h1></a
                >
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <footer class="text-center text-lg-start bg-light text-muted">
        <section
          class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
        ></section>
        <section class="">
          <div class="container text-center text-md-start mt-3">
            <div class="row mt-3">
              <div class="col-md-3 col-lg-4 col-xl-4 mx-auto mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">
                  <i class="fas fa-gem"></i>GadgetStore
                </h6>
                <p>
                  Мы всегда стремимся найти самых выгодных поставщиков, поэтому
                  наши цены такие низкие. Более 1000 клиентов по всей России,
                  попробуйте и Вы!
                </p>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">О нас</h6>
                <p>
                  <a href="about.html" class="text-reset">О компании</a>
                </p>
                <p>
                  <a href="delivery.html" class="text-reset">Доставка</a>
                </p>
                <p>
                  <a href="guarantee.html" class="text-reset">Гарантия</a>
                </p>
                <p>
                  <a href="TradeIN.html" class="text-reset">Trade In</a>
                </p>
              </div>

              <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">Контакты</h6>
                <p>
                  <i class="fas fa-home"></i> Москва, Багратионовский проезд, д.
                  7 к. 20В, Б.Ц. "Конвент", офис 711 (7 этаж)
                </p>
                <p>
                  <i class="fas fa-envelope"></i>
                  info@GadgetStore.ru
                </p>
                <p><i class="fas fa-phone"></i> 8(915)·252·58·59</p>
                <p><i class="fas fa-print"></i> 8(800)·555·35·35</p>
              </div>
            </div>
          </div>
        </section>
        <div
          class="text-center p-3"
          style="background-color: rgb(240, 239, 239)"
        >
          © 2022 Авторские права:
          <a class="text-reset fw-bold" href="https://mdbootstrap.com/"
            >NodeathMod</a
          >
        </div>
      </footer>
    </main>
{% endblock %}

store/templates/store/index.html
{% extends 'store/base.html'%}

{% load static %}

{% block content %}
<main style="background-color: rgb(247, 247, 247)">
      <div
        id="carouselExamplewdark"
        class="carousel carousel-white slide p-4 g-5 container"
        data-bs-ride="carousel"
        style="width: 57%"
      >
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="2000">
            <a href="{% url 'store:all_electronics' %}">
              <img
                src="{% static 'vendor/img/IphonePhotos/main.jpg' %}"
                class="d-block w- mx-auto"
                alt="..."
                style="border-radius: 10px"
              />
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <a href="{% url 'store:all_electronics' %}">
              <img
                src="{% static 'vendor/img/IphonePhotos/main2.jpg' %}"
                class="d-block w- mx-auto"
                alt="..."
                style="border-radius: 10px"
              />
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <a href="{% url 'store:all_electronics' %}">
              <img
                src="{% static 'vendor/img/IphonePhotos/main3.jpg' %}"
                class="d-block w- mx-auto"
                alt="..."
                style="border-radius: 10px"
              />
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <a href="{% url 'store:all_electronics' %}">
              <img
                src="{% static 'vendor/img/IphonePhotos/main4.jpg' %}"
                class="d-block w- mx-auto"
                alt="..."
                style="border-radius: 10px"
              />
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <a href="{% url 'store:all_electronics' %}">
              <img
                src="{% static 'vendor/img/IphonePhotos/main5.jpg' %}"
                class="d-block w- mx-auto"
                alt="..."
                style="border-radius: 10px"
              />
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <a href="{% url 'store:all_electronics' %}">
              <img
                src="{% static 'vendor/img/IphonePhotos/main6.jpg' %}"
                class="d-block w- mx-auto"
                alt="..."
                style="border-radius: 10px"
              />
            </a>
          </div>
          <div class="carousel-item" data-bs-interval="2000">
            <a href="{% url 'store:all_electronics' %}">
              <img
                src="{% static 'vendor/img/IphonePhotos/main7.jpg' %}"
                class="d-block w- mx-auto"
                alt="..."
                style="border-radius: 10px"
              />
            </a>
          </div>
        </div>
      </div>
      <nav class="navbar navbar-expand-lg">
        <div class="container shadow" style="background-color: #745eac">
          <div class="collapse navbar-collapse p-5" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 mx-auto">
              <li style="width: 254px; margin-right: 10px">
                <a>
                  <p1 class="fs-5 text-white fw-normal">Быстрая доставка</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Вслушайтесь и вы услышите<br />
                    как торопится наш курьер!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 0px">
                <a>
                  <p1 class="fs-5 text-white"> Простой возврат</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Мы поможем вам с этим, <br />если что-то пошло не так!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 0x">
                <a>
                  <p1 class="fs-5 text-white fw-normal"> Скидки и акции</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Каждый день, специально <br />для вас!
                  </h1></a
                >
              </li>
              <li style="width: 254px; margin-left: 10px">
                <a
                  ><p1 class="fs-5 text-white"> Консьерж-сервис</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    Помощь при выборе и эксплуатации вашего гаджета!
                  </h1>
                </a>
              </li>
              <li style="width: 254px; margin-right: 10px">
                <a
                  ><p1 class="fs-5 text-white"> Мы классные</p1>
                  <h1 class="fs-6 text-white fw-normal">
                    С нами так приятно <br />
                    иметь дело!
                  </h1></a
                >
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <footer class="text-center text-lg-start bg-light text-muted">
        <section
          class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
        ></section>
        <section class="">
          <div class="container text-center text-md-start mt-3">
            <div class="row mt-3">
              <div class="col-md-3 col-lg-4 col-xl-4 mx-auto mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">
                  <i class="fas fa-gem"></i>GadgetStore
                </h6>
                <p>
                  Мы всегда стремимся найти самых выгодных поставщиков, поэтому
                  наши цены такие низкие. Более 1000 клиентов по всей России,
                  попробуйте и Вы!
                </p>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">О нас</h6>
                <p>
                  <a href="{% url 'store:about' %}" class="text-reset">О компании</a>
                </p>
                <p>
                  <a href="{% url 'store:delivery_info' %}" class="text-reset">Доставка</a>
                </p>
                <p>
                  <a href="{% url 'store:guarantee' %}" class="text-reset">Гарантия</a>
                </p>
                <p>
                  <a href="{% url 'store:trade_in' %}" class="text-reset">Trade In</a>
                </p>
              </div>

              <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <h6 class="text-uppercase fw-bold mb-4 text-dark">Контакты</h6>
                <p>
                  <i class="fas fa-home"></i> Москва, Багратионовский проезд, д.
                  7 к. 20В, Б.Ц. "Конвент", офис 711 (7 этаж)
                </p>
                <p>
                  <i class="fas fa-envelope"></i>
                  info@GadgetStore.ru
                </p>
                <p><i class="fas fa-phone"></i> 8(915)·252·58·59</p>
                <p><i class="fas fa-print"></i> 8(800)·555·35·35</p>
              </div>
            </div>
          </div>
        </section>
        <div
          class="text-center p-3"
          style="background-color: rgb(240, 239, 239)"
        >
          © 2022 Авторские права:
          <a class="text-reset fw-bold" href="https://mdbootstrap.com/"
            >NodeathMod</a
          >
        </div>
      </footer>
    </main>
{% endblock %}